source dockerenv.sh

docker build \
	-t ${FBUILD_DOCKER_IMAGE_TAG} \
	--build-arg FBUILD_VERSION="${FBUILD_VERSION}" \
	--build-arg FBUILD_SYSTEM="${FBUILD_SYSTEM}" \
	--build-arg FBUILD_SYSTEM_VERSION="${FBUILD_SYSTEM_VERSION}" \
	--build-arg FBUILD_USERNAME="${FBUILD_USERNAME}" \
	--build-arg FBUILD_PYTHON_MAJOR_VERSION="${FBUILD_PYTHON_MAJOR_VERSION}" \
	--build-arg FBUILD_PYTHON_MINOR_VERSION="${FBUILD_PYTHON_MINOR_VERSION}" \
	--build-arg FBUILD_PYTHON_REV_VERSION="${FBUILD_PYTHON_REV_VERSION}" \
	.
