export FBUILD_VERSION=12.6.3
export FBUILD_SYSTEM=ubuntu
export FBUILD_SYSTEM_VERSION=22.04
export FBUILD_USERNAME=fapannen
export FBUILD_PYTHON_MAJOR_VERSION=3
export FBUILD_PYTHON_MINOR_VERSION=10
export FBUILD_PYTHON_REV_VERSION=0
export FBUILD_DOCKER_IMAGE_TAG=base-ml-gpu
